version: '3.0'
services:

  app:
    build: ./
    image: tuchfarber/photodb
    env_file:
      - prod.env
    depends_on:
      - mysql
    volumes:
      - static:/code/PhotoDB/photodb/static/
    networks:
      - bridgenet

  mysql:
    image: mysql
    container_name: photodb.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "PhotoDB"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bridgenet

volumes:
  static:
  mysql:

networks:
  bridgenet:
