# Generated by Django 2.0 on 2018-02-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photodb.apps.photodb.models
import uuid


class Migration(migrations.Migration):

    replaces = [('photodb', '0001_initial'), ('photodb', '0002_tag_category'), ('photodb', '0003_photo_image_hash'), ('photodb', '0004_auto_20180107_0700')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=photodb.apps.photodb.models.rename_image)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('day', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photodb.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photodb.TagCategory'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_hash',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
