# Generated by Django 2.0 on 2018-02-03 17:26

from django.db import migrations, models
import photodb.apps.photodb.models


class Migration(migrations.Migration):

    dependencies = [
        ('photodb', '0001_squashed_0004_auto_20180107_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=photodb.apps.photodb.models.rename_thumbnail),
        ),
    ]
