# Generated by Django 2.0 on 2018-02-16 04:53

from django.db import migrations, models
import photodb.apps.photodb.models


class Migration(migrations.Migration):

    dependencies = [
        ('photodb', '0002_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='medium',
            field=models.ImageField(null=True, upload_to=photodb.apps.photodb.models.rename_medium),
        ),
    ]
