# Generated by Django 2.0 on 2018-03-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photodb', '0003_photo_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='day',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='month',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
